require('dotenv').config();
const mongoose = require('mongoose');
const Medicine = require('../models/medicine.model');

const medicinesData = [
  // Common & General Medicines (Most Famous)
  {
    name: 'Paracetamol 500mg',
    genericName: 'Acetaminophen',
    category: 'Analgesics',
    stockCount: 5000,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Paracetamol 650mg',
    genericName: 'Acetaminophen',
    category: 'Analgesics',
    stockCount: 4500,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Cetirizine 10mg',
    genericName: 'Cetirizine HCl',
    category: 'Antihistamines',
    stockCount: 3250,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Cetirizine Syrup 5mg/5ml',
    genericName: 'Cetirizine HCl',
    category: 'Antihistamines',
    stockCount: 890,
    unit: 'syrup',
    isAvailable: true,
  },
  {
    name: 'Ibuprofen 200mg',
    genericName: 'Ibuprofen',
    category: 'Analgesics',
    stockCount: 3800,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Ibuprofen 400mg',
    genericName: 'Ibuprofen',
    category: 'Analgesics',
    stockCount: 3250,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Aspirin 75mg',
    genericName: 'Aspirin',
    category: 'Analgesics',
    stockCount: 2100,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Aspirin 150mg',
    genericName: 'Aspirin',
    category: 'Analgesics',
    stockCount: 1800,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Diclofenac 50mg',
    genericName: 'Diclofenac Sodium',
    category: 'Analgesics',
    stockCount: 1800,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Diclofenac Gel 1%',
    genericName: 'Diclofenac Sodium',
    category: 'Analgesics',
    stockCount: 1200,
    unit: 'gel',
    isAvailable: true,
  },
  {
    name: 'Naproxen 250mg',
    genericName: 'Naproxen',
    category: 'Analgesics',
    stockCount: 650,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Naproxen 500mg',
    genericName: 'Naproxen',
    category: 'Analgesics',
    stockCount: 540,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Loratadine 10mg',
    genericName: 'Loratadine',
    category: 'Antihistamines',
    stockCount: 2890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Fexofenadine 120mg',
    genericName: 'Fexofenadine',
    category: 'Antihistamines',
    stockCount: 1450,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Fexofenadine 180mg',
    genericName: 'Fexofenadine',
    category: 'Antihistamines',
    stockCount: 980,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Levocetirizine 5mg',
    genericName: 'Levocetirizine',
    category: 'Antihistamines',
    stockCount: 1980,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Diphenhydramine 25mg',
    genericName: 'Diphenhydramine',
    category: 'Antihistamines',
    stockCount: 1230,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole',
    category: 'Antacids',
    stockCount: 2870,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Omeprazole 40mg',
    genericName: 'Omeprazole',
    category: 'Antacids',
    stockCount: 1890,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Pantoprazole 40mg',
    genericName: 'Pantoprazole',
    category: 'Antacids',
    stockCount: 2340,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Esomeprazole 40mg',
    genericName: 'Esomeprazole',
    category: 'Antacids',
    stockCount: 1560,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Ranitidine 150mg',
    genericName: 'Ranitidine',
    category: 'Antacids',
    stockCount: 1250,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Famotidine 40mg',
    genericName: 'Famotidine',
    category: 'Antacids',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Amoxicillin 250mg',
    genericName: 'Amoxicillin',
    category: 'Antibiotics',
    stockCount: 1560,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin',
    category: 'Antibiotics',
    stockCount: 1250,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Amoxicillin 125mg Syrup',
    genericName: 'Amoxicillin',
    category: 'Antibiotics',
    stockCount: 890,
    unit: 'syrup',
    isAvailable: true,
  },
  {
    name: 'Azithromycin 250mg',
    genericName: 'Azithromycin',
    category: 'Antibiotics',
    stockCount: 1100,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Azithromycin 500mg',
    genericName: 'Azithromycin',
    category: 'Antibiotics',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Ciprofloxacin 250mg',
    genericName: 'Ciprofloxacin',
    category: 'Antibiotics',
    stockCount: 2340,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Ciprofloxacin 500mg',
    genericName: 'Ciprofloxacin',
    category: 'Antibiotics',
    stockCount: 1890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Doxycycline 100mg',
    genericName: 'Doxycycline',
    category: 'Antibiotics',
    stockCount: 567,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Metronidazole 200mg',
    genericName: 'Metronidazole',
    category: 'Antibiotics',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Metronidazole 400mg',
    genericName: 'Metronidazole',
    category: 'Antibiotics',
    stockCount: 780,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Cephalexin 250mg',
    genericName: 'Cephalexin',
    category: 'Antibiotics',
    stockCount: 670,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Cephalexin 500mg',
    genericName: 'Cephalexin',
    category: 'Antibiotics',
    stockCount: 540,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Clindamycin 300mg',
    genericName: 'Clindamycin',
    category: 'Antibiotics',
    stockCount: 450,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Amlodipine 2.5mg',
    genericName: 'Amlodipine Besylate',
    category: 'Antihypertensives',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine Besylate',
    category: 'Antihypertensives',
    stockCount: 2340,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Amlodipine 10mg',
    genericName: 'Amlodipine Besylate',
    category: 'Antihypertensives',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Losartan 25mg',
    genericName: 'Losartan Potassium',
    category: 'Antihypertensives',
    stockCount: 1200,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Losartan 50mg',
    genericName: 'Losartan Potassium',
    category: 'Antihypertensives',
    stockCount: 1890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Losartan 100mg',
    genericName: 'Losartan Potassium',
    category: 'Antihypertensives',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Metoprolol 25mg',
    genericName: 'Metoprolol Succinate',
    category: 'Antihypertensives',
    stockCount: 980,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Metoprolol 50mg',
    genericName: 'Metoprolol Succinate',
    category: 'Antihypertensives',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Metoprolol 100mg',
    genericName: 'Metoprolol Succinate',
    category: 'Antihypertensives',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Telmisartan 40mg',
    genericName: 'Telmisartan',
    category: 'Antihypertensives',
    stockCount: 1230,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Telmisartan 80mg',
    genericName: 'Telmisartan',
    category: 'Antihypertensives',
    stockCount: 980,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Metformin 500mg',
    genericName: 'Metformin HCl',
    category: 'Antidiabetics',
    stockCount: 3450,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Metformin 850mg',
    genericName: 'Metformin HCl',
    category: 'Antidiabetics',
    stockCount: 2100,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Metformin 1000mg',
    genericName: 'Metformin HCl',
    category: 'Antidiabetics',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Metformin SR 500mg',
    genericName: 'Metformin HCl',
    category: 'Antidiabetics',
    stockCount: 2340,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Glimepiride 1mg',
    genericName: 'Glimepiride',
    category: 'Antidiabetics',
    stockCount: 1200,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Glimepiride 2mg',
    genericName: 'Glimepiride',
    category: 'Antidiabetics',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Glimepiride 4mg',
    genericName: 'Glimepiride',
    category: 'Antidiabetics',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Sitagliptin 50mg',
    genericName: 'Sitagliptin',
    category: 'Antidiabetics',
    stockCount: 670,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Sitagliptin 100mg',
    genericName: 'Sitagliptin',
    category: 'Antidiabetics',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Salbutamol Inhaler 100mcg',
    genericName: 'Salbutamol',
    category: 'Bronchodilators',
    stockCount: 2340,
    unit: 'inhaler',
    isAvailable: true,
  },
  {
    name: 'Salbutamol Nebules 2.5mg',
    genericName: 'Salbutamol',
    category: 'Bronchodilators',
    stockCount: 1560,
    unit: 'nebulizer',
    isAvailable: true,
  },
  {
    name: 'Budesonide Inhaler 200mcg',
    genericName: 'Budesonide',
    category: 'Bronchodilators',
    stockCount: 890,
    unit: 'inhaler',
    isAvailable: true,
  },
  {
    name: 'Montelukast 10mg',
    genericName: 'Montelukast',
    category: 'Bronchodilators',
    stockCount: 1780,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Montelukast 4mg',
    genericName: 'Montelukast',
    category: 'Bronchodilators',
    stockCount: 890,
    unit: 'chewable tablets',
    isAvailable: true,
  },
  {
    name: 'Montelukast 5mg',
    genericName: 'Montelukast',
    category: 'Bronchodilators',
    stockCount: 670,
    unit: 'chewable tablets',
    isAvailable: true,
  },
  {
    name: 'Vitamin D3 1000IU',
    genericName: 'Cholecalciferol',
    category: 'Vitamins',
    stockCount: 4560,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Vitamin D3 2000IU',
    genericName: 'Cholecalciferol',
    category: 'Vitamins',
    stockCount: 3890,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Vitamin D3 60000IU',
    genericName: 'Cholecalciferol',
    category: 'Vitamins',
    stockCount: 2340,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Vitamin B12 500mcg',
    genericName: 'Cyanocobalamin',
    category: 'Vitamins',
    stockCount: 3890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Vitamin B12 1000mcg',
    genericName: 'Cyanocobalamin',
    category: 'Vitamins',
    stockCount: 2340,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Folic Acid 1mg',
    genericName: 'Folic Acid',
    category: 'Vitamins',
    stockCount: 4560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Folic Acid 5mg',
    genericName: 'Folic Acid',
    category: 'Vitamins',
    stockCount: 5670,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Calcium Carbonate 500mg',
    genericName: 'Calcium Carbonate',
    category: 'Vitamins',
    stockCount: 2340,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Calcium Carbonate 1000mg',
    genericName: 'Calcium Carbonate',
    category: 'Vitamins',
    stockCount: 1890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Zinc Sulfate 20mg',
    genericName: 'Zinc Sulfate',
    category: 'Vitamins',
    stockCount: 3450,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Zinc Sulfate 50mg',
    genericName: 'Zinc Sulfate',
    category: 'Vitamins',
    stockCount: 1560,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Multivitamin Tablets',
    genericName: 'Multivitamin Complex',
    category: 'Vitamins',
    stockCount: 6780,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Multivitamin Syrup',
    genericName: 'Multivitamin Complex',
    category: 'Vitamins',
    stockCount: 2340,
    unit: 'syrup',
    isAvailable: true,
  },
  {
    name: 'Vitamin C 500mg',
    genericName: 'Ascorbic Acid',
    category: 'Vitamins',
    stockCount: 8900,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Vitamin C 1000mg',
    genericName: 'Ascorbic Acid',
    category: 'Vitamins',
    stockCount: 4560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Vitamin E 400IU',
    genericName: 'Tocopherol',
    category: 'Vitamins',
    stockCount: 2340,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Magnesium 250mg',
    genericName: 'Magnesium Oxide',
    category: 'Vitamins',
    stockCount: 1670,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Fluconazole 150mg',
    genericName: 'Fluconazole',
    category: 'Antifungals',
    stockCount: 2340,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Fluconazole 50mg',
    genericName: 'Fluconazole',
    category: 'Antifungals',
    stockCount: 890,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Terbinafine 250mg',
    genericName: 'Terbinafine',
    category: 'Antifungals',
    stockCount: 1230,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Clotrimazole Cream 1%',
    genericName: 'Clotrimazole',
    category: 'Antifungals',
    stockCount: 1560,
    unit: 'cream',
    isAvailable: true,
  },
  {
    name: 'Miconazole Cream 2%',
    genericName: 'Miconazole',
    category: 'Antifungals',
    stockCount: 890,
    unit: 'cream',
    isAvailable: true,
  },
  {
    name: 'Acyclovir 200mg',
    genericName: 'Acyclovir',
    category: 'Antivirals',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Acyclovir 400mg',
    genericName: 'Acyclovir',
    category: 'Antivirals',
    stockCount: 1890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Acyclovir 800mg',
    genericName: 'Acyclovir',
    category: 'Antivirals',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Valacyclovir 500mg',
    genericName: 'Valacyclovir',
    category: 'Antivirals',
    stockCount: 1230,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Oseltamivir 75mg',
    genericName: 'Oseltamivir',
    category: 'Antivirals',
    stockCount: 890,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Clopidogrel 75mg',
    genericName: 'Clopidogrel',
    category: 'Anticoagulants',
    stockCount: 2340,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Warfarin 2mg',
    genericName: 'Warfarin Sodium',
    category: 'Anticoagulants',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Warfarin 5mg',
    genericName: 'Warfarin Sodium',
    category: 'Anticoagulants',
    stockCount: 1230,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Apixaban 2.5mg',
    genericName: 'Apixaban',
    category: 'Anticoagulants',
    stockCount: 670,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Apixaban 5mg',
    genericName: 'Apixaban',
    category: 'Anticoagulants',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Rivaroxaban 10mg',
    genericName: 'Rivaroxaban',
    category: 'Anticoagulants',
    stockCount: 540,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Rivaroxaban 20mg',
    genericName: 'Rivaroxaban',
    category: 'Anticoagulants',
    stockCount: 760,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Sertraline 25mg',
    genericName: 'Sertraline',
    category: 'Antipsychotics',
    stockCount: 1200,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Sertraline 50mg',
    genericName: 'Sertraline',
    category: 'Antipsychotics',
    stockCount: 1870,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Sertraline 100mg',
    genericName: 'Sertraline',
    category: 'Antipsychotics',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Escitalopram 5mg',
    genericName: 'Escitalopram',
    category: 'Antipsychotics',
    stockCount: 980,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Escitalopram 10mg',
    genericName: 'Escitalopram',
    category: 'Antipsychotics',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Escitalopram 20mg',
    genericName: 'Escitalopram',
    category: 'Antipsychotics',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Fluoxetine 20mg',
    genericName: 'Fluoxetine',
    category: 'Antipsychotics',
    stockCount: 1340,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Fluoxetine 40mg',
    genericName: 'Fluoxetine',
    category: 'Antipsychotics',
    stockCount: 890,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Duloxetine 30mg',
    genericName: 'Duloxetine',
    category: 'Antipsychotics',
    stockCount: 890,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Duloxetine 60mg',
    genericName: 'Duloxetine',
    category: 'Antipsychotics',
    stockCount: 670,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Atorvastatin 10mg',
    genericName: 'Atorvastatin',
    category: 'Cardiovascular',
    stockCount: 3450,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Atorvastatin 20mg',
    genericName: 'Atorvastatin',
    category: 'Cardiovascular',
    stockCount: 2890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Atorvastatin 40mg',
    genericName: 'Atorvastatin',
    category: 'Cardiovascular',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Rosuvastatin 5mg',
    genericName: 'Rosuvastatin',
    category: 'Cardiovascular',
    stockCount: 1890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Rosuvastatin 10mg',
    genericName: 'Rosuvastatin',
    category: 'Cardiovascular',
    stockCount: 2890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Rosuvastatin 20mg',
    genericName: 'Rosuvastatin',
    category: 'Cardiovascular',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Furosemide 20mg',
    genericName: 'Furosemide',
    category: 'Diuretics',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Furosemide 40mg',
    genericName: 'Furosemide',
    category: 'Diuretics',
    stockCount: 1870,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Spironolactone 25mg',
    genericName: 'Spironolactone',
    category: 'Diuretics',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Spironolactone 50mg',
    genericName: 'Spironolactone',
    category: 'Diuretics',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Allopurinol 100mg',
    genericName: 'Allopurinol',
    category: 'Gout',
    stockCount: 1230,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Allopurinol 300mg',
    genericName: 'Allopurinol',
    category: 'Gout',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Colchicine 0.5mg',
    genericName: 'Colchicine',
    category: 'Gout',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Gabapentin 100mg',
    genericName: 'Gabapentin',
    category: 'Neurology',
    stockCount: 1200,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Gabapentin 300mg',
    genericName: 'Gabapentin',
    category: 'Neurology',
    stockCount: 1560,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Gabapentin 400mg',
    genericName: 'Gabapentin',
    category: 'Neurology',
    stockCount: 890,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Pregabalin 75mg',
    genericName: 'Pregabalin',
    category: 'Neurology',
    stockCount: 1230,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Pregabalin 150mg',
    genericName: 'Pregabalin',
    category: 'Neurology',
    stockCount: 890,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Carbamazepine 200mg',
    genericName: 'Carbamazepine',
    category: 'Neurology',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Levodopa 100mg',
    genericName: 'Levodopa',
    category: 'Neurology',
    stockCount: 540,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Thyroxine 25mcg',
    genericName: 'Levothyroxine',
    category: 'Endocrinology',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Thyroxine 50mcg',
    genericName: 'Levothyroxine',
    category: 'Endocrinology',
    stockCount: 2340,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Thyroxine 100mcg',
    genericName: 'Levothyroxine',
    category: 'Endocrinology',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Prednisolone 5mg',
    genericName: 'Prednisolone',
    category: 'Steroids',
    stockCount: 1890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Prednisolone 10mg',
    genericName: 'Prednisolone',
    category: 'Steroids',
    stockCount: 1230,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Dexamethasone 0.5mg',
    genericName: 'Dexamethasone',
    category: 'Steroids',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Dexamethasone 4mg',
    genericName: 'Dexamethasone',
    category: 'Steroids',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Hydroxychloroquine 200mg',
    genericName: 'Hydroxychloroquine',
    category: 'Immunomodulators',
    stockCount: 2340,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Methotrexate 2.5mg',
    genericName: 'Methotrexate',
    category: 'Immunomodulators',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Azathioprine 50mg',
    genericName: 'Azathioprine',
    category: 'Immunomodulators',
    stockCount: 670,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Tretinoin Cream 0.025%',
    genericName: 'Tretinoin',
    category: 'Dermatology',
    stockCount: 890,
    unit: 'cream',
    isAvailable: true,
  },
  {
    name: 'Adapalene Gel 0.1%',
    genericName: 'Adapalene',
    category: 'Dermatology',
    stockCount: 1230,
    unit: 'gel',
    isAvailable: true,
  },
  {
    name: 'Clindamycin Gel 1%',
    genericName: 'Clindamycin',
    category: 'Dermatology',
    stockCount: 1560,
    unit: 'gel',
    isAvailable: true,
  },
  {
    name: 'Benzoyl Peroxide Gel 2.5%',
    genericName: 'Benzoyl Peroxide',
    category: 'Dermatology',
    stockCount: 1200,
    unit: 'gel',
    isAvailable: true,
  },
  {
    name: 'Benzoyl Peroxide Gel 5%',
    genericName: 'Benzoyl Peroxide',
    category: 'Dermatology',
    stockCount: 1890,
    unit: 'gel',
    isAvailable: true,
  },
  {
    name: 'Mupirocin Ointment 2%',
    genericName: 'Mupirocin',
    category: 'Dermatology',
    stockCount: 890,
    unit: 'ointment',
    isAvailable: true,
  },
  {
    name: 'Hydrocortisone Cream 1%',
    genericName: 'Hydrocortisone',
    category: 'Dermatology',
    stockCount: 2340,
    unit: 'cream',
    isAvailable: true,
  },
  {
    name: 'Betamethasone Cream 0.05%',
    genericName: 'Betamethasone',
    category: 'Dermatology',
    stockCount: 670,
    unit: 'cream',
    isAvailable: true,
  },
  {
    name: 'Clobetasol Ointment 0.05%',
    genericName: 'Clobetasol',
    category: 'Dermatology',
    stockCount: 540,
    unit: 'ointment',
    isAvailable: true,
  },
  {
    name: 'Tobramycin Eye Drops 0.3%',
    genericName: 'Tobramycin',
    category: 'Ophthalmology',
    stockCount: 890,
    unit: 'eye drops',
    isAvailable: true,
  },
  {
    name: 'Moxifloxacin Eye Drops 0.5%',
    genericName: 'Moxifloxacin',
    category: 'Ophthalmology',
    stockCount: 670,
    unit: 'eye drops',
    isAvailable: true,
  },
  {
    name: 'Latanoprost Eye Drops 0.005%',
    genericName: 'Latanoprost',
    category: 'Ophthalmology',
    stockCount: 1230,
    unit: 'eye drops',
    isAvailable: true,
  },
  {
    name: 'Timolol Eye Drops 0.5%',
    genericName: 'Timolol',
    category: 'Ophthalmology',
    stockCount: 890,
    unit: 'eye drops',
    isAvailable: true,
  },
  {
    name: 'Artificial Tears Eye Drops',
    genericName: 'Carboxymethylcellulose',
    category: 'Ophthalmology',
    stockCount: 4560,
    unit: 'eye drops',
    isAvailable: true,
  },
  {
    name: 'Dextromethorphan Syrup',
    genericName: 'Dextromethorphan',
    category: 'Cough & Cold',
    stockCount: 2340,
    unit: 'syrup',
    isAvailable: true,
  },
  {
    name: 'Guaifenesin Syrup',
    genericName: 'Guaifenesin',
    category: 'Cough & Cold',
    stockCount: 1890,
    unit: 'syrup',
    isAvailable: true,
  },
  {
    name: 'Ambroxol Syrup',
    genericName: 'Ambroxol',
    category: 'Cough & Cold',
    stockCount: 2780,
    unit: 'syrup',
    isAvailable: true,
  },
  {
    name: 'Cetirizine Syrup',
    genericName: 'Cetirizine',
    category: 'Cough & Cold',
    stockCount: 1560,
    unit: 'syrup',
    isAvailable: true,
  },
  {
    name: 'Phenylephrine Nasal Drops',
    genericName: 'Phenylephrine',
    category: 'Cough & Cold',
    stockCount: 890,
    unit: 'nasal drops',
    isAvailable: true,
  },
  {
    name: 'Xylometazoline Nasal Spray',
    genericName: 'Xylometazoline',
    category: 'Cough & Cold',
    stockCount: 1230,
    unit: 'nasal spray',
    isAvailable: true,
  },
  {
    name: 'Domperidone 10mg',
    genericName: 'Domperidone',
    category: 'Gastrointestinal',
    stockCount: 2340,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Ondansetron 4mg',
    genericName: 'Ondansetron',
    category: 'Gastrointestinal',
    stockCount: 1890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Ondansetron 8mg',
    genericName: 'Ondansetron',
    category: 'Gastrointestinal',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Dicyclomine 20mg',
    genericName: 'Dicyclomine',
    category: 'Gastrointestinal',
    stockCount: 1230,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Bisacodyl 5mg',
    genericName: 'Bisacodyl',
    category: 'Gastrointestinal',
    stockCount: 890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Lactulose Syrup',
    genericName: 'Lactulose',
    category: 'Gastrointestinal',
    stockCount: 1560,
    unit: 'syrup',
    isAvailable: true,
  },
  {
    name: 'ORS Powder',
    genericName: 'Oral Rehydration Salts',
    category: 'Gastrointestinal',
    stockCount: 8900,
    unit: 'sachet',
    isAvailable: true,
  },
  {
    name: 'Ferrous Sulfate 200mg',
    genericName: 'Ferrous Sulfate',
    category: 'Vitamins',
    stockCount: 2340,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Ferrous Ascorbate 100mg',
    genericName: 'Ferrous Ascorbate',
    category: 'Vitamins',
    stockCount: 1890,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Calcium with Vitamin D3',
    genericName: 'Calcium Carbonate + Vitamin D3',
    category: 'Vitamins',
    stockCount: 3450,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Biotin 10mg',
    genericName: 'Biotin',
    category: 'Vitamins',
    stockCount: 890,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Omega-3 1000mg',
    genericName: 'Fish Oil',
    category: 'Supplements',
    stockCount: 2340,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Glucosamine 1500mg',
    genericName: 'Glucosamine',
    category: 'Supplements',
    stockCount: 1560,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Chondroitin 1200mg',
    genericName: 'Chondroitin',
    category: 'Supplements',
    stockCount: 890,
    unit: 'capsules',
    isAvailable: true,
  },
  {
    name: 'Melatonin 3mg',
    genericName: 'Melatonin',
    category: 'Sleep Aids',
    stockCount: 1230,
    unit: 'tablets',
    isAvailable: true,
  },
  {
    name: 'Zolpidem 10mg',
    genericName: 'Zolpidem',
    category: 'Sleep Aids',
    stockCount: 670,
    unit: 'tablets',
    isAvailable: true,
  },
];

(async () => {
  try {
    const connectionURL = process.env.DB_CONNECTION_STRING;
    if (!connectionURL) {
      throw new Error(
        'DB_CONNECTION_STRING not found in environment variables',
      );
    }

    await mongoose.connect(connectionURL);
    console.log('✅ Connected to MongoDB');

    // Check if medicines already exist
    const existingCount = await Medicine.countDocuments();
    if (existingCount > 0) {
      console.log(
        `⚠️  Found ${existingCount} existing medicines. Deleting all...`,
      );
      await Medicine.deleteMany({});
      console.log('✅ All existing medicines deleted');
    }

    // Insert all medicines
    const result = await Medicine.insertMany(medicinesData);
    console.log(
      `✅ Successfully seeded ${result.length} medicines to database!`,
    );

    // Display statistics
    const stats = await Medicine.aggregate([
      { $group: { _id: '$category', count: { $sum: 1 } } },
      { $sort: { count: -1 } },
    ]);

    console.log('\n📊 Category Distribution:');
    stats.forEach((stat) => {
      console.log(`  ${stat._id}: ${stat.count} medicines`);
    });

    const totalStock = await Medicine.aggregate([
      { $group: { _id: null, total: { $sum: '$stockCount' } } },
    ]);
    console.log(`\n📦 Total Stock Count: ${totalStock[0]?.total || 0} units`);

    const available = await Medicine.countDocuments({ isAvailable: true });
    const unavailable = await Medicine.countDocuments({ isAvailable: false });
    console.log(`✅ Available Medicines: ${available}`);
    console.log(`❌ Unavailable Medicines: ${unavailable}`);

    
    const samples = await Medicine.find().limit(5);
    console.log('\n📋 Sample Medicines:');
    samples.forEach((med) => {
      console.log(
        `  - ${med.name} (${med.category}) - Stock: ${med.stockCount} ${med.unit}`,
      );
    });

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding medicines:', error.message);
    if (error.code === 11000) {
      console.error(
        'Duplicate key error. Please check for duplicate medicine names.',
      );
    }
    process.exit(1);
  }
})();
